require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/BlockComments:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Rails/FilePath:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/Rails/HttpStatus:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Rails/RedundantForeignKey:
  Enabled: false










